version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
build_script:
- dotnet build slack-bot/slack-bot.sln -c Release -v q /nologo
- dotnet publish slack-bot/ArtsBot/ArtsBot.csproj -c Release -o ../bin --no-build
test_script:
- dotnet slack-bot/bin/ArtsBot.dll
