version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
build_script:
- dotnet publish slack-bot/ArtsBot/ArtsBot.csproj -c Release -o ..\bin
test_script:
- dotnet run slack-bot/bin/ArtsBot.dll
